### ISSUE TITLE
Add some new algo like rx2

### ISSUE THREAD

**Issue by bilalin** [maribun20/termux-miner#3]
Hello can you add new algo for lux coin like Randomx2.

**Comment by maribun20** [comment]
Ok, my be not for now.
And i need to learn about rx2 algos can work on linux x86, x64, and arm
linux.

Pada tanggal Jum, 12 Mar 2021 00.27, bilalin ***@***.***>
menulis:

**Comment by maribun20** [comment]
Mybe later
