### ISSUE TITLE
Please add support arm OpenCL gpu also..

### ISSUE THREAD

**Issue by Saikatsaha1996** [maribun20/termux-miner#4]
Really nice miner.. getting good performance
But everyone developed miner for arm cpu
But now every mobile support OpenCL gpu
Can you please add OpenCL gpu for arm Mali and Adreno ?..🙏

**Comment by maribun20** [comment]
Dear users:

I'am so sorry, i'cant add gpu mining support for ARM cpu's.
because is realy realy hard.
and actually gpu mining is doesn't supported on any ARM devices.
and mybe gpu mining on ARM devices is not supported forever.
Thankyou.

regards:

maribun20

**Comment by Saikatsaha1996** [comment]
> Dear users:
> 
> I'am so sorry, i'cant add gpu mining support for ARM devices. because is realy realy hard. and actually gpu mining is doesn't supported on any ARM devices. mybe ARM devices only support with cpu mining only. and mybe gpu mining on ARM devices is not supported forever. Thankyou.
> 
> regards:
> 
> maribun20

Already working with arm OpenCL GPu
