### ISSUE TITLE
Algo SCRYPTN2 and ARGON2 unkown

### ISSUE THREAD

**Issue by BitMaci** [maribun20/termux-miner#5]
When I run the miner with scryptn2 algo in termux, it gives me "Unknown algo parameter "scryptn2", but I see that is supported, the same happens with argon2 algo. Any advice please?

**Comment by maribun20** [comment]
Dear users:

scryptn2 algo, only availiable on branch master an newer releases file.
and for argon2 i have search reference how to add argon2 algo to my miner.

regards
maribun20
